### ISSUE TITLE
[Organizer Request] Add Utsab Sapkota to Kathmandu chapter

### ISSUE THREAD

**Issue by utsab818** [cncf/communitygroups#134] opened 2024-08-03 08:34 UTC
### Name of chapter inquiring about

`CNCF Kathmandu`

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Name: Utsab Sapkota
Email: utsabsapkota4231@gmail.com
GitHub: https://github.com/utsab818
LinkedIn: https://www.linkedin.com/in/utsab-sapkota-3741581ba/

Bio:
I am a passionate student focused on Cloud Native, DevOps, and Open Source, particularly in Kubernetes ☸. I am dedicated to leveraging my skills to innovate and streamline software development processes. With hands-on experience in container orchestration and cloud-native technologies, I am eager to contribute to projects that embrace modern DevOps practices. Currently, I am contributing to KubeVirt, an incubating CNCF project. My expertise lies in Kubernetes and Go.

### Tell us why you want to be added or removed from the chapter

I would like to join as the Co-organizer of CNCF Kathmandu on the recommendation of the current `CNCF Kathmandu Lead` for the following reasons:

* **Passionate About Cloud Native Technologies:** This aligns perfectly with my interests and expertise.
* **Knowledge Sharing:** I aim to help others learn and grow in cloud-native technologies.
* **Networking Opportunities:** This role will allow me to network with professionals and experts in the industry.
* **Support Local Community:** I am dedicated to growing the local cloud-native community in Kathmandu.
* **Encouraging Open Source Contributions:** I wish to inspire others to contribute to open source projects.
* **Leadership Role:** I am excited about planning and executing community events effectively.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment] 2024-09-19 20:17
Hello @utsab818 - thank you for submitting this request.

it looks like you have already been a speaker for this chapter, and are labeling yourself as a co-organizer on LinkedIn. That said, let me copy the current organizer, @RashikaKarkito to have her confirm you should join as a co-organizer, or if there are other steps she wishes you take ahead.

**Comment by RashikaKarki** [comment] 2024-09-28 05:11
Hey @AudMonte01 ,
I can confirm and excited to have him onboard as co-organizer.

**Comment by AudMonte01** [comment] 2024-12-11 21:14
It looks as though the above question has been resolved. I will close this issue/ticket.

Best regards,
Audra

**Closed by AudMonte01** 2024-12-11 21:14 UTC
